HWKAPM-773 - Documented the usage of OpenShift env vars
hawkular/hawkular-apm-user-guide pull request #25
Opened 2016-12-02 13:49 UTC by jpkrohling

2016-12-02 14:05 UTC, objectiser requested changes

2016-12-02 14:05 UTC, objectiser commented on docs/contributors/opentracingprovider.adoc
> +A free-format value that ties this request to a specific service. When the application is executed in OpenShift, this defaults to a value that is derived from the environment variable `OPENSHIFT_BUIL
Shouldn't it also mention the HAWKULAR_APM_SERVICE_NAME as a container independent env variable, and what is precedence is to the OPENSHIFT... vars?

2016-12-02 14:05 UTC, objectiser commented on docs/contributors/opentracingprovider.adoc
> +value is `foo.bar`
Need to make it clear that the service name is independent of the specific version number?

2016-12-02 14:05 UTC, objectiser commented on docs/instrumentation/jvmagent.adoc
> +Once the Hawkular APM distribution zip has been unpacked, you will find a folder called *_apm_*. This folder contains the necessary environment script and agent jar(s) to configure a client JVM envir
Not sure what changed here?

2016-12-02 14:05 UTC, objectiser commented on docs/contributors/opentracingprovider.adoc
> +NOTE: The ‘nodeId’ represents a composite of target fragment’s ‘fragmentId’ field and a sequence of indexes to locate the target node within the tree. For example, “abcd:0:2” represents a node in fra
Not sure what changed here?

2016-12-02 14:05 UTC, objectiser commented on docs/contributors/opentracingprovider.adoc
> +A free-format value that ties this request to a specific service. When the application is executed in OpenShift, this defaults to a value that is derived from the environment variable `OPENSHIFT_BUIL
Saw it is listed in the table below - but may be best to also describe here due to the dependency between the env vars if both set.

2016-12-02 14:14 UTC, jpkrohling commented on docs/instrumentation/jvmagent.adoc
> +Once the Hawkular APM distribution zip has been unpacked, you will find a folder called *_apm_*. This folder contains the necessary environment script and agent jar(s) to configure a client JVM envir
Trailing space, it seems. I blame Atom for that :)

2016-12-02 14:14 UTC, jpkrohling commented on docs/contributors/opentracingprovider.adoc
> +NOTE: The ‘nodeId’ represents a composite of target fragment’s ‘fragmentId’ field and a sequence of indexes to locate the target node within the tree. For example, “abcd:0:2” represents a node in fra
Trailing space, I'll revert this.

2016-12-06 09:17 UTC, objectiser approved these changes

2016-12-06 09:17 UTC, objectiser commented
@jpkrohling sorry for delay in re-reviewing - can you rebase as seem to be some conflicts, and then we can merge.

2016-12-06 10:06 UTC, jpkrohling commented
Rebased.

2016-12-06 10:23 UTC, merged

2016-12-06 10:23 UTC, objectiser commented
@jpkrohling Thanks!